### ISSUE TITLE
Clases Abstractas

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#13]
No me quedo clara la explicación de las **clases abstractas**. En limpio según la documentación:

> Las clases abstractas son clases que no se instancian y sólo pueden ser heredadas, trasladando así un funcionamiento obligatorio a clases hijas. Mejoran la calidad del código y ayudan a reducir la cantidad de código duplicado.

1. Cómo mejoran la calidad del código?
2. Si una clase hereda de una **abstracta** y ésta tiene un **método abstracto**, debe ser definido en la clase hija verdad?

Con un ejemplo entendería más rápido, pero los que he encontrado son poco claros 😞

**Comment by cristofer-dev** [comment]
Piensa en una APP que gestiona `Usuarios`, `Clientes`, `Pedidos`, `Proveedores`

Ambos necesitan **CRUD** respectivo a su motor de persistencia (DB) por tanto ambos necesitan 
- `insert`
- `select`
- `update`
- `delete`

Usemos el DELETE de ejemplo, esto significa que en cada **CLASE** tendrias que tener algo como esto

     public function delete() {
        $sql = "DELETE FROM clientes WHERE cliente_id = ?";
        $datos = array($this->$pid);
        ejecutar_query($sql, $datos);
    }

Esto para **DELETE**, **INSERT**, **SELECT** y **UPDATE** para cada clase del sistema.

Quedaria algo asi ( para el **delete** )

    class Usuario  {
        public function delete() {
            $sql = "DELETE FROM usuario WHERE usuario_id = ?";
            $datos = array($this->$pid);
            ejecutar_query($sql, $datos);
        }
    }

    class Cliente  {
        public function delete() {
            $sql = "DELETE FROM cliente WHERE cliente = ?";
            $datos = array($this->$pid);
            ejecutar_query($sql, $datos);
        }
    }


    class Pedido  {
         public function delete() {
            $sql = "DELETE FROM pedido WHERE pedido_id = ?";
            $datos = array($this->$pid);
            ejecutar_query($sql, $datos);
        }
    }

    class Proveedor {
         public function delete() {
            $sql = "DELETE FROM proveedor WHERE proveedor_id = ?";
            $datos = array($this->$pid);
            ejecutar_query($sql, $datos);
        }
    }

Se parecen en algo los 4 metodos de esas 4 clases ?
lo único que cambia es la tabla y el campo de busqueda, por tanto podriamos hacer una clase *Abstracta* que funcionara para cualquier clase, quizas algo como esto:
    
    abstract class StandardObject { 
        
        public function delete() {
            $tabla = strtolower(get_class($this));
            $pid = "{$tabla}_id";
            $sql = "DELETE FROM $tabla WHERE $pid = ?";
            $datos = array($this->$pid);
            ejecutar_query($sql, $datos);
        }
    }

El Metodo de esta clase, por si sólo **obtendra el nombre de la clase a la cual pertenece** (de la cual sera llamado) asi, cuando es llamado desde la clase Cliente, obtendra "Cliente", cuando es llamado desde la clase Pedido, obtendra "Pedido", la propiedad id es el nombre de la clase + `_id` (esta nomenclatura dependera de la BD y del ORM que la gestione, pero suele existir una definida, sea cual sea deberia poder hacerse algo parecido).

Luego usando ambos valores genera la sentencia SQL, y de esta forma , el DELETE podria ser llamado desde cualquier clase y este genera la sentencia SQL correcta y la ejecuta a la BD.

Sólo nos falta heredar esta clase quedaria algo asi

    class Cliente extends StandardObject { 
        # 
    }

Así la clase `Cliente` hereda de la clase `Abstracta` llamada  `StandardObject` todos sus metodos, en este caso el DELETE, y ya no lo debemos declarar, simplemente llamarlo y este automaticamente ejecuta el metodo.

El método puede ser sobre escrito o redefinido, pero eso es cuando un objeto en particular tiene alguna variación y necesitas ajustar el metodo unicamente para esa clase. ( el mundo no es perfecto ), pero aún así te ahorras muchas lineas de código.

Ahora , súmale los métodos faltantes y te ahorras de escribir 4 métodos en cada clase, además de controlar errores, dado que si un SQL falla, fallara para todos, pero si esta bien escrito tambien funcionara para todos, minimizas los puntos de fallas y ademas reutilizas código.

Al Margen: Se le dice abstracta por que no se puede instanciar, dado que esta pensada para usar el nombre de la clase hija, por tanto pierde sentido si se genera una instancia de esta clase, sólo sirve para ser heredada

**Comment by rodpoblete** [comment]
WOW! Awesome Example! 🔥 🔥 
Se entiende mucho más el concepto con un **buen ejemplo**, que con 10 párrafos de teoría. 😃 
Thanks! 👍

**Comment by DMaster69** [comment]
nada que aportar a la gran respuesta de @cristofer-dev
