### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#14]
Esto se usa en the real life? lo pregunto porque obligan a una clase a emplearlos.
Según la documentación promueven un entorno de desarrollo. 🤷‍

**Comment by DMaster69** [comment]
Si, se usan bastante las interfaces. 
Ahora la diferencia con una Clase abstracta es que te obliga a implementar el método pero no tiene un comportamiento común definido.
Esto sucede cuando quieres exigir ciertas clases compartan un método en común pero su implementación es demasiado diferente como para compartir el método de una clase abstracta. 

Si no sobrescribes un método declarado en una clase abstracta utiliza el comportamiento definido en clase abstracta. Por eso utilizas la interfaz para obligar a una clase a implementar el método que necesitas. no soy tan bueno explicando como @cristofer-dev pero espero se entienda con este [ejemplo que encontré en internet ](https://sicutdeux.wordpress.com/2011/06/27/diferencia-entre-clases-abstractas-e-interfaces-php/)

```
interface interaccion {
    public function encender() {}
}

class lampara implements interaccion {
    //Heredada de la Interfaz
    public function encender() {
        //propia forma de encender
    }
}

class automovil implements interaccion {
    //Heredada de la Interfaz
    public function encender() {
        //mi implementación de encendido
    }
}
```
Saludos!

**Comment by rodpoblete** [comment]
Se entiende perfecto! muy clara la diferencia respecto a la clase abstracta.
Gracias :smile: !
