### ISSUE TITLE
MySQLi procedural

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#17]
mysqli procedimental se ocupa realmente en entornos de desarrollo?, porque según la documentación su rendimiento y aplicación es muy limitada respecto a las demás alternativas (mysqli POO o PDO derechamente)

**Comment by cristofer-dev** [comment]
A que te refieres con **mysqli procedimental** ??

**Comment by cristofer-dev** [comment]
Ya cache!

POO por lo general te da varias cosas a favor, y PDO es como MySQLi pero OO, caso práctico, la reutilización de sentencias del ejemplo de la Clase Abstracta de la #13 Cosa que no podrias lograr con MySQLi

**Comment by rodpoblete** [comment]
para transparentar, me explico mejor: con la extensión **mysqli** uso funciones para realizar tareas. No instancio objetos, ni ocupo métodos, funciones puritas. Ej: **Procedimental** archivo `00-mysqli-procedimental.php`:

```
<?php

/* Conectar */
$mysqli = mysqli_connect('127.0.0.1', 'admin', 'malajamala', 'tienda');

/* Verificar la conexión */
if (mysqli_connect_errno($mysqli)) {
    echo 'Falló al conectar a MySQL:' . mysqli_connect_error();
}

/* Ejecutar la sentencia SQL */
$resultado = mysqli_query($mysqli, "SELECT nombre, precio FROM productos");

/* Imprimir filas */
while ($fila = mysqli_fetch_assoc($resultado)) {
    echo $fila['nombre'] . ' cuesta ' . $fila['precio'] . PHP_EOL;
}

/* Liberar memoria (opcional) */
mysqli_free_result($resultado);

/* Cerrar la conexión */
mysqli_close($mysqli);
```

**VS de la manera orientada a objetos** con la misma extensión **mysqli** archivo `01-mysqli-orientado-a-objetos.php`:

```
<?php

/* Conectar */
$mysqli = new mysqli('127.0.0.1', 'admin', 'malajamala', 'tienda');

/* Verificar la conexión */
if ($mysqli->connect_errno) {
    echo 'Falló al conectar MySQL: ' . $mysqli->connect_error . PHP_EOL;
}

/* Ejecutar la sentencia SQL */
$resultado = $mysqli->query("SELECT nombre, precio FROM productos");

/* Imprimir filas */
while ($fila = $resultado->fetch_assoc()) {
    echo $fila['nombre'] . ' cuesta ' . $fila['precio'] . PHP_EOL;
}

/* Liberar memoria (opcional) */
$resultado->free();

/* Cerrar la conexión */
$mysqli->close();
```

**Comment by rodpoblete** [comment]
Ahh ok, el ejemplo de las clases abstractas del otro día. ;)

**Comment by DMaster69** [comment]
ya no se usa, POO y PDO es lo que se usa actualmente

**Comment by rodpoblete** [comment]
Gracias @DMaster69
