### ISSUE TITLE
Liberar memoria como buena práctica?

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#18]
En el curso mencionan pasos para una conexión satisfactoria:
1. Conectar
2. Check conexión
3. Execute sentencia SQL
4. Usar datos
5. **Liberar memoria (opcional)**
6. **Cerrar la conexión**

entre lineas mencionan que los puntos **5** y **6** son opcionales y que PHP los puede hacer por ti, pero no queda claro.

**Comment by cristofer-dev** [comment]
Ni idea que se podia hacer eso! :/

**Comment by DMaster69** [comment]
en la actualidad la mayoría de las Librerías o Framework te abstraen de ese tipo de funcionalidades, pero en aplicaciones de alto rendimiento es bueno liberar la memoria.

**Comment by rodpoblete** [comment]
Perfect, gracias!
