### ISSUE TITLE
¿ Que estas usando como referencia ?

### ISSUE THREAD

**Issue by cristofer-dev** [rodpoblete/php-trainer#2]
Tus commits van guiados por el contenido de un curso? libro ? documentación del lenguaje ?

**Comment by rodpoblete** [comment]
No.Sólo por referencia del articulo que alguna vez vimos. [How To Write a Git Commit Message](https://chris.beams.io/posts/git-commit/)
Si encuentro que son poco **atómicos**. No se si concuerdas con eso.

**Comment by cristofer-dev** [comment]
Me explique mal! Me referia al contenido de PHP... onda... por que emepzaste con variables ? y luego con lo demas ? Sigues  el contenido de un curso? libro ? documentación del lenguaje ?

**Comment by rodpoblete** [comment]
Ahh si. Sigo el temario del curso por eso del orden. Igual lo voy a subir al **REAME.MD** para que quede más ordenado.

**Comment by cristofer-dev** [comment]
Cool!
