### ISSUE TITLE
¿Cómo funciona projects en github?

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#4]
Cómo funciona la pestaña **projects**? es un tablero similar a meistertask que puedes agregar tarreas directo ahí?

**Comment by rodpoblete** [comment]
además la ficha **milestone**  a la derecha tampoco cacho para que sirve :sob: 
![image](https://user-images.githubusercontent.com/8984133/34487186-f727fd08-efb1-11e7-9d71-ad258f17d27a.png)

**Comment by cristofer-dev** [comment]
Basicamente es un tablero como "trello" o como "meister" para organizar el trabajo... un repo puede tener multiples "proyectos" y adicionalmente puedes "automatizar" onda... las issues nuevas entran en inbox... las cerradas pasan a close y las reopen pasan a "working"

Pero puedes hacer todo eso manual. [ docu aquí](https://help.github.com/articles/about-project-boards/)

Los **Milestone** son Hitos, o puntos de control o "entregas" o como quieras llamarles, y puedes asociar las issue a determinados "milestones" asi puedes saber que issues abordar primero según el milestone en el cual pretendes terminar primero [Docu](https://help.github.com/articles/about-milestones/)

Sin prejuicio de lo anterior, el manejo con issues es bastante eficiente, a veces no es neccesario el kanban y todas esas cosas, pero por si las necesitas, estan ahi! Onda te evitas la pajita de tener que usar otra app adicional para ver tu kanban.

Eso!

**Comment by rodpoblete** [comment]
cool! gracias! :sunglasses:
