### ISSUE TITLE
Type Hinting

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#7]
Encontré muy útil esto. Alguno la ha usado en la pega o algún proyecto real?
Poder especificar el tipo de dato que recibimos de un parámetro, y si éste no coincide PHP arroja un error con las penas del infierno. (Izquierda **editor**, derecha **terminal**)
![image](https://user-images.githubusercontent.com/8984133/34753762-7a268940-f598-11e7-9d45-e25c91248866.png)

**Comment by cristofer-dev** [comment]
Lo he usado en POO, según yo es buena practica, pero el error se debe controlar no debe "explotar".

**Comment by DMaster69** [comment]
Tener en cuenta que Laravel también ha sabido aprovechar bien ese nuevo feature, por lo cual entenderlo ahora será un plus cuando comiences a ver **Laravel**. Reitero lo dicho por cristofer sobre capturar el error

**Comment by rodpoblete** [comment]
Cool! thanks!
