### ISSUE TITLE
include && require

### ISSUE THREAD

**Issue by rodpoblete** [rodpoblete/php-trainer#9]
Según entendí en PHP hay varias formas de agregar archivos: 

- `require()`
- `require_once()`
- `include()`
- `include_once()`

Me corrigen si estoy equivocado:

1. **include**

> Inserta un código procedente de otro archivo, en caso de que dicho archivo no exista o tenga errores, el programa mostrará un **warning pero seguirá funcionando**

2. **require**

> Similiar a include, pero en este caso, si el archivo no existe o contiene errores, el programa no funcionará y obtendremos un **fatal error en el log**

3. **include_once** && **require_once**

> Funcionan de la misma forma que las definiciones de arriba, salvo que impiden la carga de un mismo fichero varias veces. _(se me ocurre para cachear errores)_

Cuando utilizar uno u otro en la práctica?. A simple vista me tinca que **_once** se podría usar cuando el programa tenga dimensiones considerables y se llame al archivo varias veces.

**Comment by cristofer-dev** [comment]
Según yo:
1.- `require`, asi explota y te enteras... si pusiste un `require` es por que se necesita para algo, y si falla la carga explotara en algún momento. ( es la historia de controlar la propagación de errores de nuevo )

2.- I don't know! Sugiero ver la performance de cada una, hay que darle una vuelta!

**Comment by DMaster69** [comment]
Como lo dice la descripción de la función, si es necesario que el archivo lo cargue siempre usa `require`, así como dice @cristofer-dev te enteras al explotar y mata el proceso, si lo que hace ese archivo no es 100% necesario para el proceso y puede seguir funcionando sin lograr ejecutar el `include`. esa es la pequeña diferencia con respecto a lo que dijo cristofer.
Si, si pusiste el archivo en un `include` o `require `es por que algo de el necesitas, pero si eso que necesitas detiene el proceso usa `require`, si es necesario pero no destruye el proceso usa `include`.
por mi parte siempre utilizo el _once así me aseguro que no se cargue más de una vez

**Comment by rodpoblete** [comment]
Ok, perfecto, gracias! Dudas aclaradas con ambas explicaciones. :smile:
